config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from detector.views import TextInputView, FeedbackCreateView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from django.urls import reverse
from assignment.views import (
    AssignmentListView,
    AssignmentCreateView,
    AssignmentDetailView,
    PriceView,
    ExampleCreateView,
    AssignmentUpdateView
)

from killgpt.users.views import (
    step_one_signup_teacher,
    step_one_signup_student, 
    step_two_signup,
    subscription_confirm,
    profile_view,
)
class HomeSitemap(Sitemap):
    def items(self):
        return ['home']

    def location(self, item):
        return reverse(item)
sitemaps = {
    'home': HomeSitemap,
}


urlpatterns = [
    path(
        "landing", TemplateView.as_view(template_name="pages/landing.html"), name="landing"
    ),

    path(
        "step2.5", TemplateView.as_view(template_name="steps/twoplan.html"), name="step-2.5"
    ),
    path("subscription-confirm/", subscription_confirm, name="subscription_confirm"),
    path("profile/", profile_view, name="profile"),
    path(
        "step1", step_two_signup, name="step-1"
    ),
    path(
        "step2", TemplateView.as_view(template_name="steps/two.html"), name="step-2"
    ),
    path(
        "step3", PriceView, name="step-3"
    ),
    path(
        "entrance", TemplateView.as_view(template_name="pages/entrance.html"), name="entrance"
    ),
    path(
        "student-info", step_one_signup_student, name="student"
    ),
    path(
        "teacher-info", step_one_signup_teacher, name="teacher"
    ),
    path(
        "", TemplateView.as_view(template_name="pages/landing_real.html"), name="landing2"
    ),
    path(
        "assignment", AssignmentListView.as_view(), name="assignment-list"
    ),

    path(
        "assignment/<int:pk>/update/",
        AssignmentUpdateView.as_view(),
        name="assignment-update",
    ),
    path("assignment/uploadexample/<int:pk>", ExampleCreateView.as_view(), name="example-create"),
    path("assignment/new/", AssignmentCreateView.as_view(), name="assignment-create"),
    path("detector/", TextInputView, name="home"),
    # path("AI/", TextInputView, name='AI'),
    path(
        "assignment/<int:pk>/",
        AssignmentDetailView.as_view(),
        name="assignment-detail",
    ),
    path(
        "tos/", TemplateView.as_view(template_name="pages/terms.html"), name="terms"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "pp/", TemplateView.as_view(template_name="pages/privacy.html"), name="pp"
    ),
    path(
        "about/", FeedbackCreateView.as_view(), name="about"
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("killgpt.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('api-auth/', include('rest_framework.urls')),
    # path('detect/', include(detector_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

killgpt/users/urls.py
from django.urls import path

from killgpt.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:email>/", view=user_detail_view, name="detail"),
]

detector/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from assignment.models import Assignment
# class TextInputForm(forms.Form):
#     text_input = forms.CharField(label= "", widget=forms.Textarea(attrs={'rows': 12, 'cols': 50, 'class': 'custom-field', 'placeholder': 'Enter the text you want to test for AI/Chatbot plagiarism (minimum 20 words).', 'style': 'background-color: #FFF8DB; color: black; font-family: Source Code Pro;'} ))

from .models import Feedback

class TextInputForm(forms.Form):
    text_input = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'rows': 10,
            'cols': 35,
            'class': 'custom-field border-black',
            'placeholder': 'Enter the text you want to test for AI/Chatbot text (minimum 20 words)',
            'style': 'background-color: #201A31; color: white; font-family: Poppins, sans-serif; font-size: 14px; border-color: white;',
        }),
        label='Text Input:',  # Set the label for the field
    )
    file_input = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'custom-file-input',
            'id': 'customFile',
            'style': 'background-color: #201A31; color: white; font-family: Poppins, sans-serif; font-size: 14px;',
            'multiple': True,
        }),
        label='File Input:',  # Set the label for the field
    )
   
    feedback_input = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={
            'class': 'custom-checkbox',
        }),
        label='Do you want also want help marking this assignment?',
        required=False
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        assignments = Assignment.objects.filter(user=user)  # Fetch assignments for the current user
        #assignments = Assignment.objects.all()  # Fetch assignments for the current user
        assignment_choices = [(assignment.pk, assignment.assignment_title) for assignment in assignments]
        
        self.fields['feedback_choice'] = forms.ChoiceField(
            choices=assignment_choices,
            widget=forms.Select(attrs={'class': 'feedback-choice', 'style': 'display:none;'}),
            label='Assignment Choice',
            required=False
        )
    # feedback_choice = forms.ChoiceField(
    #     choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')],
    #     widget=forms.Select(attrs={'class': 'feedback-choice', 'style': 'display:none;'}),
    #     label='Do you want writing feedback if this is human text?',
    #     required=False
    # )
    # grade_level = forms.ChoiceField(
    #     choices=[('english_11', 'English 11'),('history_11', 'History 12'), ('history_IB', 'IB History'), ('english_IB', 'IB English'),],
    #     required=False,
    #     label='What class is this for?'
        
    #     )
    # # rubric items 
    # rubric_field = forms.ChoiceField(
    #     choices=[('coherence', 'Coherence'),('WS', 'Writing Structure'), ('Persp', 'Perspecitves'), ('TF', 'Thoughfulness'),],
    #     required=False,
    #     label='What section of the rubric do you want to evaluate?'
        
    #     )
    

    def clean(self):
        cleaned_data = super().clean()
        text_input = cleaned_data.get('text_input')
        file_input = cleaned_data.get('file_input')
        if not text_input and not file_input:
            raise forms.ValidationError('Either a text input or a file input is required')
        elif text_input and file_input:
            raise forms.ValidationError('Only one of text input or file input can be submitted')
        if text_input: 
            word_count = len(text_input.split())
            if word_count < 20:
                raise ValidationError(_('The text input must be at least 20 words.'), code='invalid')
        return cleaned_data

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['Name','Email',"Title", "Content"]

        # widgets = {
        #     "Name": forms.TextInput(attrs={"class": "form-control", 'rows': 12, 'cols': 4, 'class': 'custom-field', 'placeholder': 'Enter your text...', 'style': 'background-color: #FFF8DB; color: black; font-family: Source Code Pro;'}),
        #     "Email": forms.TextInput(attrs={"class": "form-control", 'rows': 12, 'cols': 4, 'class': 'custom-field', 'placeholder': 'Enter your text...', 'style': 'background-color: #FFF8DB; color: black; font-family: Source Code Pro;'}),
        #     "Title": forms.TextInput(attrs={"class": "form-control", 'rows': 12, 'cols': 4, 'class': 'custom-field', 'placeholder': 'Enter your text...', 'style': 'background-color: #FFF8DB; color: black; font-family: Source Code Pro;'}),
        #     "Content": forms.Textarea(attrs={"class": "form-control", 'rows': 12, 'cols': 50, 'class': 'custom-field', 'placeholder': 'Enter your text...', 'style': 'background-color: #FFF8DB; color: black; font-family: Source Code Pro;'}),
        # }
        widgets = {
            'Name': forms.TextInput(attrs={'class': 'form-control'}),
            'Email': forms.TextInput(attrs={'class': 'form-control'}),
            'Title': forms.TextInput(attrs={'class': 'form-control'}),
            'Content': forms.Textarea(attrs={'class': 'form-control','rows': 2, 'cols': 4,}),
        }

killgpt/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from .forms import EmailSignupForm, PasswordSignupForm
from django.contrib import messages
from django.http import HttpResponseRedirect
User = get_user_model()

from django.contrib.auth.decorators import login_required
from django.urls import reverse

from djstripe.settings import djstripe_settings
from djstripe.models import Subscription

import stripe

def profile_view(request):
    return render(request, 'steps/profile.html',)


@login_required
def subscription_confirm(request):
    # set our stripe keys up
    stripe.api_key = djstripe_settings.STRIPE_SECRET_KEY

    # get the session id from the URL and retrieve the session object from Stripe
    session_id = request.GET.get("session_id")
    session = stripe.checkout.Session.retrieve(session_id)

    # get the subscribing user from the client_reference_id we passed in above
    client_reference_id = int(session.client_reference_id)
    subscription_holder = get_user_model().objects.get(id=client_reference_id)
    # sanity check that the logged in user is the one being updated
    assert subscription_holder == request.user

    # get the subscription object form Stripe and sync to djstripe
    subscription = stripe.Subscription.retrieve(session.subscription)
    djstripe_subscription = Subscription.sync_from_stripe_data(subscription)

    # set the subscription and customer on our user
    subscription_holder.subscription = djstripe_subscription
    subscription_holder.customer = djstripe_subscription.customer
    subscription_holder.save()

    # show a message to the user and redirect
    messages.success(request, f"You've successfully signed up. Thanks for the support!")
    return HttpResponseRedirect(reverse("assignment-list"))

from django.shortcuts import render, redirect
from .forms import UserSignupForm  # Import your forms

def step_one_signup_teacher(request):
    if request.method == 'POST':
        form = EmailSignupForm(request.POST)
        if form.is_valid():
            # Save email in session or temporary storage
            request.session['signup_email'] = form.cleaned_data['email']
            return redirect('step-1')  # Redirect to the password step
            
    else:
        form = EmailSignupForm(request.POST)
    
    return render(request, 'pages/teacher.html', {'form': form})

def step_one_signup_student(request):
    if request.method == 'POST':
        form = EmailSignupForm(request.POST)
        if form.is_valid():
            # Save email in session or temporary storage
            request.session['signup_email'] = form.cleaned_data['email']
            return redirect('step-1')  # Redirect to the password step
            
    else:
        form = EmailSignupForm(request.POST)
    
    return render(request, 'pages/student.html', {'form': form})


from django.contrib.auth import authenticate, login

from django.contrib import messages

def step_two_signup(request):
    if 'signup_email' not in request.session:
        return redirect('signup_email')  # Redirect to email step if email is not available

    if request.method == 'POST':
        form = PasswordSignupForm(request.POST)
        if form.is_valid():
            email = request.session.get('signup_email')
            password = form.cleaned_data['password']
            
            # Check if the email is already associated with a user
            if User.objects.filter(email=email).exists():
                messages.warning(request, 'Email is already registered. Please use a different email.')
                return render(request, 'steps/one.html', {'form': form, 'email': email})
            
            # Create the user with the collected email and password
            user = User.objects.create_user(email=email, password=password, username=email)
            
            # Authenticate the user
            user = authenticate(request, username=email, password=password)
            
            if user is not None:
                # Log in the user
                login(request, user)
                return redirect('step-2')  # Redirect to success page or any desired page
            else:
                # Handle the case where authentication fails
                # You might want to add an error message or redirect to a login page
                return render(request, 'login_error.html')
    else:
        try:
            email = request.session.get('signup_email')
        except:
            email = ""

        form = PasswordSignupForm(initial={'email': email})
        
    return render(request, 'steps/one.html', {'form': form, 'email': email})
class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "email"
    slug_url_kwarg = "email"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

killgpt/templates/pages/contact.html
{% extends "base.html" %}

{% load i18n %}



{% block content %}
<style>
    .gradient-text {
      background: linear-gradient(to right, #00ffff, #ff00cc);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
  </style>
<div class="text col-md-8 offset-md-2 text-center">
    <h1 class="text-white text-center py-4" style="font-weight: 700;">Your <span class="gradient-text"> Journey</span> Shouldn't End Here</h1> 
    
<p2 class="text-white text-center" style="font-size: 1.1em;
color: #fff;
font-weight: 400;
max-width: 700px;">Contact us with any inquiries you have about recruitment, feedback, or implementing our product in your school.</p2>
<div class=" pt-2 text-center">
    <a href="mailto:dilreetraju@gmail.com" style ='background-color: aqua;'>Email Us</a>
</div>
</div>
    


{% endblock %}

killgpt/templates/pages/entrance.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="text-white pt-0 pb-4 text-center">
    <h3 style="font-size: 3em;"> Are you a</h3>
</div>
<style>
    /* Custom styles for the links */
    .custom-link {
    display: inline-block;
    padding: 25% 25%;
    text-decoration: none;
    color: #231250;
    border-radius: 5px;
    font-weight: bold;
    font-size: 2em;
    letter-spacing: 2px;
    transition: all 0.2s ease; /* Updated transition for all properties */
    }

    .custom-link:hover {
    letter-spacing: 6px;
    box-shadow: 0 0 20px 0 rgba(255, 255, 255, 0.7); /* White glow effect */
    }

    /* Colors for the links */
    .aqua-bg {
      background-color: aqua;
    }
    .magenta-bg {
      background-color: magenta;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-5 text-center">
        <a href="{% url 'student' %}" class="custom-link aqua-bg btn btn-lg text">Student</a>
      </div>
      <div class="col-md-1 text-white d-flex justify-content-center align-items-center"><h4 class="or-separator">or</h4></div>
      <div class="col-md-5 text-center">
        
        <a href="{% url 'teacher' %}" class="custom-link magenta-bg btn btn-lg">Educator</a>
      </div>
    </div>
  </div>
</body>

{% endblock content %}

killgpt/templates/pages/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .form-container {
      width: 15%;
      margin: 0 auto;
    }
    :root {
        --background-color-secondary: #231250;
    }

    .no-pad {
        padding: 0px;
    }

    .pie {
        margin: 8px;
        height: 180px;
        width: 180px;
        border-radius: 50%;
    }

    .one {
        background: conic-gradient(dodgerblue 0% 85%,
                orangered 25% 85%,
                limegreen 85% 93%,
                #f9f000 93%);
    }

    .two {
        background: conic-gradient(cornflowerblue 0% 35%,
                darkorange 35% 57%,
                greenyellow 57% 85%,
                #FFFFFF 85%);
    }

    .three {

        background: conic-gradient(#03D1CA 0% var(--percentage),
                #231250 0%);
    }

    .pie.hollow {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .pie.hollow::after {
        content: '';
        position: absolute;
        height: 180px;
        width: 180px;
        border-radius: 25%;
        background-color: #FFFFFF;
    }

    .pie.two.hollow::after {
        content: '';
        position: absolute;
        height: 48px;
        width: 48px;
        border-radius: 25%;
        background-color: var(--background-color-secondary);
    }

    .pie.three.hollow::after {
        content: '';
        position: absolute;
        height: 120px;
        width: 120px;
        border-radius: 50%;
        background-color: var(--background-color-secondary);
    }
    :root {
      --background-color: #231250;
      --text-color: white;

    }
    .pie.hollow span {
        font-size: 28pt;
        z-index: 2;
        color: white;
        font-weight: bold;
        font-family: "JetBrains Mono", sans-serif;
    }
    .card {
      background-color: var(--background-color);
      border: none;
  }

    .progress {
        margin-bottom: 10px; /* Adjust the margin to create spacing between graphs */
    }
    table {
            border: 1px solid white;
            width: 100%;
            background-color: var(--background-color);
            color: var(--text-color);
        }

        th, td {
            border: 1px solid white;
            text-align: left;
            padding: 10px;
        }
    </style>
       <link rel="preconnect" href="https://fonts.googleapis.com">
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kanit&family=Source+Code+Pro&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Your+Font+Name&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<link href="{% static 'css/style.css'%}" rel="stylesheet">
<main role="main py-4" style="background: var(--background-color);">
    
   <div class="container pt-5 pb-2 font-weight-bold" style="font-family: Poppins, sans-serif;">
    <div class=" pt-2 container col-md-8 rounded ">
   <h2 class="display-4 text-center"style='font-size: 5em;
   font-weight: 800;
   color: #fff;
   line-height: 1em;
   text-transform: uppercase;font-family: Poppins, sans-serif; text-transform: uppercase; font-size: 36px; color: var(--text-color);'>Let's End Wrongful AI Use With Hesiod.</h2>



  
<hr class="bg-white">

   {% if output%}
      
      <div class="row pt-5 gy-2">
        <div class="col-md-4">
          <div class="card h-100" style="background-color: magenta; color: #231250;">
            <div class="card-body">
                <p class="card-text">Humanity Score</p>
                <h4 class="card-title py-4 bold" style="font-weight: 700;">{{score}}</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card h-100" style="background-color: magenta; color: #231250;">
            <div class="card-body">
                <p class="card-text">Decision</p>
                <h4 class="card-title py-4 bold" style="font-weight: 700;">{{decision}}</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card h-100" style="background-color: magenta; color: #231250;">
            <div class="card-body">
                <p class="card-text">Percent Certainty</p>
                <h4 class="card-title py-4 bold" style="font-weight: 700;">{{percent }}%</h4>
            </div>
          </div>
        </div>  
  </div>
  <hr class="bg-white">
{% if feedback %}
<div class="d-flex  row justify-content-center">
 
  <div class="text-center my-2 col-md-5">
    <div class="col-md-12">
        <div class="text-center">
          <h3 class="text-white">
            Marks
           </h3>
        </div>
        <div class="d-flex justify-content-center align-items-center m-1">
            <div class="pie hollow three" style="--percentage: {{ display_mark }}%;">
              <span>{{marks}}</span>
          </div>
        </div>
    </div>
   
  </div>

<div class="col-md-5 d-flex align-items-center">
  <style>
    #hiddenButtons {
        display: none;
    }
  </style>
  
  <div class="container ">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center">
        <button id="toggleButton" class="btn btn-lg w-30 py-3 mb-3" style="background-color: white; font-size: 16px; color: #231250;"
                onclick="toggleButtons()"> Is the score not what you expected?
        </button>
    </div>
  </div>
  
  <div id="hiddenButtons" class="row">
    <div class="col-md-6">
        <a href="#" style="text-decoration: none;">
            <div class="row align-items-center pt-2">
                <div class="col-md-12">
                    <button class="btn btn-lg w-100 d-flex py-3 justify-content-center align-items-center"
                            style="background-color: white; font-size: 16px; color: #231250;"
                            onclick="buttonAction('high')">Is the mark too high?
                    </button>
                </div>
            </div>
        </a>
    </div>
  
    <div class="col-md-6">
        <a href="#" style="text-decoration: none;">
            <div class="row align-items-center pt-2">
                <div class="col-md-12">
                    <button class="btn btn-lg w-100 d-flex py-3 justify-content-center align-items-center"
                            style="background-color: white; font-size: 16px; color: #231250;"
                            onclick="buttonAction('low')">Is the mark too low?
                    </button>
                </div>
            </div>
        </a>
    </div>
  </div>
  </div>
  
  <script>
  function toggleButtons() {
    var hiddenButtons = document.getElementById("hiddenButtons");
    hiddenButtons.style.display = (hiddenButtons.style.display === "none") ? "flex" : "none";
  }
  
  function buttonAction(feedback) {
    alert("Is the score not what you expected?\nFeedback: " + feedback);
  }
  </script>
</div>
    
</div>

<hr class="bg-white">
<div class="row d-flex pt-4 justify-content-center gx-5">
  <div class="col-md-5 rounded m-1 text-white" style="background-color: #2A1855;">
    <h4 class="text-info text-uppercase m-3">
      Feedback
    </h4>
    <hr class="bg-white">
    <p class="text-white">
      {{feedback|linebreaks}}
    </p>

  </div>
  <div class="col-md-5 rounded m-1 text-white" style="background-color: #2A1855;">
    <h4 class="text-info text-uppercase m-3">
      General Advice
    </h4>
    <hr class="bg-white">
    <p class="text-white">
      {{gen_advice|linebreaks}}
    </p>

  </div>
</div>
{% endif %}

{% endif %}
  
    

   
   
   <form action="" method="POST" class = 'text-white input-lg py-5'enctype="multipart/form-data" style=" background: var(--background-color);">
        
    {% csrf_token %}
    
    <div class="form-content">
      {{ form|crispy }}
  </div>
    <p class="mt-0 text-white"style='font-family: Poppins, sans-serif; font-size: 10px;'>We support pdf, word, and txt file types. However, ensure to remove all images, idenitification, and cover pages to support our document requirements. </p>
    <p class=" text-left text-white"style=" font-family: Poppins, sans-serif;font-size: 12px;">By submitting content, you agree to our <a href="{% url 'terms' %}" target="_blank" class="">Terms of Use</a> and <a href="{% url 'pp' %}" class=""target="_blank">Privacy Policy</a>. Be sure you have appropriate rights to the content before using the AI Text Classifier.  Also, ensure that all personal information should be purged from any files/text being submitted for analysis.</p>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
          const feedbackToggle = document.querySelector('#id_feedback_input');
          const feedbackLabel = document.querySelector('[for="id_feedback_choice"]');
          const feedbackChoice = document.querySelector('.feedback-choice');
  
          const toggleFeedback = () => {
              const arbitraryValue = 'What Assignment Is This Submission For?'; // Change this to your desired label text
              
              if (feedbackToggle.checked) {
                  feedbackLabel.textContent = arbitraryValue;
                  feedbackChoice.style.display = 'block';
              } else {
                  feedbackLabel.textContent = ''; // Default label text
                  feedbackChoice.style.display = 'none';
              }
          };
  
          toggleFeedback();
  
          feedbackToggle.addEventListener('change', toggleFeedback);
      });
  </script>
    <button id="submit-button" class="btn block px-5 text-black" type="submit" style="display: inline-block;
    font-size: 1em;
    background: aqua;
    padding: 10px 30px;
    text-transform: uppercase;
    text-decoration: none;
    font-weight: 500;
    margin-top: 10px;
    color: #111;
    letter-spacing: 2px;
    transition: 0.2s;">{% bs_icon 'search' color='black' size='1em' %} Analyze</button>
    <button id="loading-spinner" class="btn px-5 text-black" type="button" style="background: aqua; font-family: Poppins, sans-serif; font-size: 14px; border: w#4E527F;display: none;">
      <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      Analyzing...
    </button>
    <script>
      $(document).ready(function(){
        $('#submit-button').click(function(){
          $('#submit-button').hide();
          $('#loading-spinner').show();
        });
      });
      </script>
      <script>
        // Get references to the checkbox and additional field
        const checkbox = document.getElementById('id_checkbox_field');
        const additionalField = document.getElementById('id_additional_field');
    
        // Hide the additional field initially
        additionalField.style.display = 'none';
    
        // Add an event listener to the checkbox
        checkbox.addEventListener('change', function () {
            if (checkbox.checked) {
                // If the checkbox is checked, show the additional field
                additionalField.style.display = 'block';
            } else {
                // If the checkbox is unchecked, hide the additional field
                additionalField.style.display = 'none';
            }
        });
    </script>
    
      </form>


    
    
    

 <hr class="bg-white">

  
</div>
     
  </main>

{%endblock content%}

killgpt/templates/pages/privacy.html
<h1>Privacy Policy</h1>


<h4>Stored Data
</h4>
<p>We do not store any of the content uploaded into Hesiod. Consequently, no samples of imputed writing are kept on our servers. 
</p>

<h4>Use of Cookies</h4>
<p>We do not use any cookies on our website. Therefore, we do not collect any information about your device or browsing behavior.
</p>

<h4>Information Security</h4>
<p>We take reasonable measures to protect the security of your information. We do not store any data or information about our users, so there is no risk of unauthorized access or disclosure of any personal information.
</p>

<h4>Third-Party Links</h4>
<p>Our website may contain links to third-party websites that are not under our control. We are not responsible for the privacy practices or content of those websites.
</p>

<h4>Changes to Privacy Policy
</h4>
<p>We reserve the right to modify this Privacy Policy at any time without notice. Please review this Privacy Policy periodically to stay informed about our privacy practices.
</p>

<h4>Contact Information
</h4>
<p>If you have any questions or concerns about our Privacy Policy, please contact us at d.raju@hesiod.ca.</p>

<p>We hope this Privacy Policy provides you with clear information about how we protect your privacy when you use our AI chatbot detector website.</p>